// Generated by Browser Recorder
// Recording: GitHub Login Flow
// Date: 2026-06-10T05:20:00.000Z
// Steps: 6

import { test, expect } from '@playwright/test';

test('GitHub Login Flow', async ({ page }) => {
  await page.waitForTimeout(500);
  // Navigate to: Sign in to GitHub
  await page.goto('https://github.com/login');
  await page.locator('#login_field').fill("user@example.com");
  await page.locator('#password').fill("password123");
  await page.waitForTimeout(600);
  await page.locator('[name="commit"]').click(); // Sign in
  await expect(page.locator('.Header')).toBeVisible();
  await page.screenshot({ path: 'logged-in.png', fullPage: true });
});