/**
 * Browser Recorder - Script Generator
 * Converts recorded actions into clean, maintainable Playwright test scripts.
 */
import {
  Recording,
  RecordingStep,
  GeneratorOptions,
  GeneratedScript,
  NavigateStep,
  ClickStep,
  DblClickStep,
  InputStep,
  SelectStep,
  CheckStep,
  UploadStep,
  KeydownStep,
  HoverStep,
  AssertStep,
  ScreenshotStep,
} from './types';

export function generateScript(recording: Recording, options: GeneratorOptions): GeneratedScript {
  const opts = resolveOptions(options);
  const lines: string[] = [];
  const imports = new Set<string>();
  const variables = new Map<string, string>();
  let indent = '  ';
  let varCounter = 0;

  // ── Header ──────────────────────────────────────────
  lines.push(`// Generated by Browser Recorder`);
  lines.push(`// Recording: ${escapeComment(recording.title)}`);
  lines.push(`// Date: ${recording.recordedAt}`);
  lines.push(`// Steps: ${recording.steps.length}`);
  lines.push('');

  // ── Imports ─────────────────────────────────────────
  if (opts.format === 'test') {
    lines.push(`import { test, expect } from '@playwright/test';`);
  } else {
    lines.push(`const { chromium } = require('playwright');`);
  }
  lines.push('');

  // ── Extract variables ───────────────────────────────
  if (opts.parameterize) {
    extractVariables(recording, variables);
    if (variables.size > 0) {
      for (const [name, value] of variables) {
        lines.push(`const ${name} = ${JSON.stringify(value)};`);
      }
      lines.push('');
    }
  }

  // ── Main test/function ──────────────────────────────
  const fnName = sanitizeName(recording.title);
  if (opts.format === 'test') {
    lines.push(`test('${escapeComment(recording.title)}', async ({ page }) => {`);
  } else {
    lines.push(`(async () => {`);
    lines.push(`${indent}const browser = await chromium.launch();`);
    lines.push(`${indent}const context = await browser.newContext();`);
    if (opts.screenshotOnFailure) {
      lines.push(`${indent}const page = await context.newPage();`);
    } else {
      lines.push(`${indent}const page = await context.newPage();`);
    }
  }

  // Filter out consecutive navigations to same URL
  const steps = deduplicateNavigations(recording.steps);

  // Generate step code
  for (let i = 0; i < steps.length; i++) {
    const step = steps[i];
    const nextStep = steps[i + 1];

    // Smart wait between steps (if there's a time gap)
    if (opts.smartWait && shouldInsertWait(step, nextStep)) {
      const waitMs = Math.min(step.timestamp || 500, 3000);
      if (waitMs >= 300) {
        lines.push(`${indent}await page.waitForTimeout(${waitMs});`);
      }
    }

    const stepCode = generateStep(step, indent, variables);
    if (stepCode) {
      lines.push(...stepCode);
    }
  }

  // Footer
  if (opts.format === 'script') {
    lines.push('');
    lines.push(`${indent}await browser.close();`);
    lines.push(`})();`);
  } else {
    if (opts.screenshotOnFailure) {
      lines.push('');
      lines.push(`${indent}// Screenshot on failure is handled by Playwright config`);
    }
    lines.push(`});`);
  }

  const code = lines.join('\n');
  const filename = `${fnName}.spec.ts`;

  return { filename, code, imports: Array.from(imports), variables };
}

function resolveOptions(options: GeneratorOptions): Required<GeneratorOptions> {
  return {
    format: options.format || 'test',
    framework: options.framework || 'playwright',
    parameterize: options.parameterize ?? true,
    smartWait: options.smartWait ?? true,
    defaultWait: options.defaultWait || 500,
    screenshotOnFailure: options.screenshotOnFailure ?? false,
  };
}

// ── Step Generators ───────────────────────────────────────

function generateStep(
  step: RecordingStep,
  indent: string,
  variables: Map<string, string>
): string[] | null {
  switch (step.type) {
    case 'navigation':
      return generateNavigation(step as NavigateStep, indent);
    case 'click':
      return generateClick(step as ClickStep, indent);
    case 'dblclick':
      return generateDblClick(step as DblClickStep, indent);
    case 'input':
      return generateInput(step as InputStep, indent, variables);
    case 'select':
      return generateSelect(step as SelectStep, indent, variables);
    case 'check':
      return generateCheck(step as CheckStep, indent);
    case 'upload':
      return generateUpload(step as UploadStep, indent);
    case 'keydown':
      return generateKeydown(step as KeydownStep, indent);
    case 'hover':
      return generateHover(step as HoverStep, indent);
    case 'wait':
      return [`${indent}await page.waitForTimeout(${step.ms || 1000});`];
    case 'assert':
      return generateAssert(step as AssertStep, indent, variables);
    case 'screenshot':
      return generateScreenshot(step as ScreenshotStep, indent);
    default:
      return [`${indent}// Unknown step type: ${(step as any).type}`];
  }
}

function generateNavigation(step: NavigateStep, indent: string): string[] {
  const out: string[] = [];
  if (step.title) {
    out.push(`${indent}// Navigate to: ${escapeComment(step.title)}`);
  }
  out.push(`${indent}await page.goto('${escapeString(step.url)}');`);
  return out;
}

function generateClick(step: ClickStep, indent: string): string[] {
  const locator = buildLocator(step.selector);
  const comment = step.text ? ` // ${escapeComment(step.text.substring(0, 40))}` : '';
  return [`${indent}await ${locator}.click();${comment}`];
}

function generateDblClick(step: DblClickStep, indent: string): string[] {
  const locator = buildLocator(step.selector);
  return [`${indent}await ${locator}.dblclick();`];
}

function generateInput(
  step: InputStep,
  indent: string,
  variables: Map<string, string>
): string[] {
  const locator = buildLocator(step.selector);

  // Check if value is a variable
  let valueExpr: string;
  const varName = findVariableForValue(step.value, variables);
  if (varName) {
    valueExpr = varName;
  } else {
    valueExpr = JSON.stringify(step.value);
  }

  // Password fields: use fill but don't inline the actual value in a comment
  const isPassword = step.inputType === 'password';
  const comment = isPassword ? '' : '';

  if (step.inputType === 'file') {
    return [`${indent}await ${locator}.setInputFiles(${valueExpr});`];
  }

  // Clear first, then fill
  if (step.value === '') {
    return [`${indent}await ${locator}.clear();`];
  }

  return [
    `${indent}await ${locator}.fill(${valueExpr});${comment}`,
  ];
}

function generateSelect(
  step: SelectStep,
  indent: string,
  variables: Map<string, string>
): string[] {
  const locator = buildLocator(step.selector);
  const varName = findVariableForValue(step.value, variables);
  const valueExpr = varName || JSON.stringify(step.value);
  return [`${indent}await ${locator}.selectOption(${valueExpr});`];
}

function generateCheck(step: CheckStep, indent: string): string[] {
  const locator = buildLocator(step.selector);
  if (step.checked) {
    return [`${indent}await ${locator}.check();`];
  } else {
    return [`${indent}await ${locator}.uncheck();`];
  }
}

function generateUpload(step: UploadStep, indent: string): string[] {
  const locator = buildLocator(step.selector);
  const filesExpr = JSON.stringify(step.files);
  return [`${indent}await ${locator}.setInputFiles(${filesExpr});`];
}

function generateKeydown(step: KeydownStep, indent: string): string[] {
  if (step.key === 'Enter') {
    const locator = step.selector ? buildLocator(step.selector) : 'page';
    return [`${indent}await ${locator}.press('Enter');`];
  }
  if (step.key === 'Tab') {
    return [`${indent}await page.keyboard.press('Tab');`];
  }
  if (step.key === 'Escape') {
    return [`${indent}await page.keyboard.press('Escape');`];
  }
  if (step.key === 'ArrowDown') {
    return [`${indent}await page.keyboard.press('ArrowDown');`];
  }
  if (step.key === 'ArrowUp') {
    return [`${indent}await page.keyboard.press('ArrowUp');`];
  }
  return [`${indent}await page.keyboard.press('${escapeString(step.key)}');`];
}

function generateHover(step: HoverStep, indent: string): string[] {
  const locator = buildLocator(step.selector);
  return [`${indent}await ${locator}.hover();`];
}

function generateAssert(step: AssertStep, indent: string, variables: Map<string, string>): string[] {
  const locator = buildLocator(step.selector);

  switch (step.assertType) {
    case 'visible':
      return [`${indent}await expect(${locator}).toBeVisible();`];
    case 'hidden':
      return [`${indent}await expect(${locator}).toBeHidden();`];
    case 'text': {
      const expected = step.expected ? findVariableForValue(String(step.expected), variables) || JSON.stringify(String(step.expected)) : '""';
      return [`${indent}await expect(${locator}).toHaveText(${expected});`];
    }
    case 'value': {
      const expected = step.expected ? findVariableForValue(String(step.expected), variables) || JSON.stringify(String(step.expected)) : '""';
      return [`${indent}await expect(${locator}).toHaveValue(${expected});`];
    }
    case 'count': {
      const count = step.expected || 1;
      return [`${indent}await expect(${locator}).toHaveCount(${count});`];
    }
    case 'url':
      return [`${indent}await expect(page).toHaveURL(/.*/);`];
    case 'title':
      return [`${indent}await expect(page).toHaveTitle(/.*/);`];
    default:
      return [`${indent}await expect(${locator}).toBeVisible();`];
  }
}

function generateScreenshot(step: ScreenshotStep, indent: string): string[] {
  const label = step.label ? escapeComment(step.label) : 'screenshot';
  return [`${indent}await page.screenshot({ path: '${label}.png', fullPage: true });`];
}

// ── Helpers ───────────────────────────────────────────────

function buildLocator(selector: string): string {
  if (!selector) return 'page';

  // Playwright-specific selector formats: role=, text=, :has-text()
  if (
    selector.startsWith('role=') ||
    selector.startsWith('text=') ||
    selector.includes(':has-text(')
  ) {
    return `page.locator('${escapeString(selector)}')`;
  }

  // Standard CSS selectors use page.locator()
  return `page.locator('${escapeString(selector)}')`;
}

function escapeString(str: string): string {
  return str.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}

function escapeComment(str: string): string {
  return str.replace(/\n/g, ' ').trim();
}

function sanitizeName(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .substring(0, 60) || 'recording';
}

function shouldInsertWait(current: RecordingStep, next?: RecordingStep): boolean {
  if (!next) return false;
  const gap = (next.timestamp || 0) - (current.timestamp || 0);
  return gap >= 500;
}

function deduplicateNavigations(steps: RecordingStep[]): RecordingStep[] {
  return steps.filter((step, i) => {
    if (step.type !== 'navigation') return true;
    if (i === 0) return true;
    const prev = steps[i - 1];
    if (prev.type === 'navigation' && (prev as NavigateStep).url === (step as NavigateStep).url) {
      return false;
    }
    return true;
  });
}

// ── Variable Extraction ───────────────────────────────────

function extractVariables(recording: Recording, variables: Map<string, string>) {
  const valueCounts = new Map<string, number>();

  for (const step of recording.steps) {
    if (step.type === 'input' || step.type === 'select') {
      const val = (step as InputStep | SelectStep).value;
      if (!val || val.length < 2) continue;
      // Skip one-character values, they're usually not meaningful variables
      if (val.length === 1) continue;
      valueCounts.set(val, (valueCounts.get(val) || 0) + 1);
    }
  }

  let counter = 0;
  for (const [value, count] of valueCounts) {
    // Only extract values that appear 2+ times
    if (count >= 2 && value.length >= 2) {
      const name = guessVariableName(value, counter);
      if (!Array.from(variables.values()).includes(value)) {
        variables.set(name, value);
        counter++;
      }
    }
  }
}

function guessVariableName(value: string, counter: number): string {
  // email pattern
  if (/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(value)) return 'email';
  // URL pattern
  if (/^https?:\/\//.test(value)) return 'url';
  // Numeric value
  if (/^\d+$/.test(value)) return 'count';
  if (/^\d+\.\d+$/.test(value)) return 'amount';

  // Generate from content
  const cleaned = value.toLowerCase().replace(/[^a-z0-9]+/g, '_').substring(0, 20);
  if (cleaned.length > 1) return cleaned;

  return `value${counter + 1}`;
}

function findVariableForValue(value: string, variables: Map<string, string>): string | null {
  for (const [name, val] of variables) {
    if (val === value) return name;
  }
  return null;
}
